### ISSUE TITLE
When try to fill an non partial OTC order, the site refresh

### ISSUE THREAD

**Issue by joseJRJR** [galacticcouncil/HydraDX-ui#1060] opened 2024-02-28 17:10 UTC
Like the title said, if you try to sign a non partial order, the site refresh

https://github.com/galacticcouncil/HydraDX-ui/assets/123791232/670eeaa5-5c51-478a-b0ca-2c357add790f

**Comment by jak-pan** [comment] 2024-04-11 08:08
Duplicate of #836

**Closed by jak-pan** 2024-04-11 08:08 UTC
