### ISSUE TITLE
MM Split trade bug

### ISSUE THREAD

**Issue by green-jay** [galacticcouncil/HydraDX-ui#766] opened 2023-11-24 15:22 UTC
How to reproduce:

- Connect Metamask
- Do a Split trade
- Place trade -> Sign transaction

![Image](https://github.com/galacticcouncil/HydraDX-ui/assets/75261756/10a7a455-da2d-401e-824f-c36a31d30d4b)

**Comment by mrq1911** [comment] 2023-11-27 13:31
which asset combination you trade?

**Comment by nohaapav** [comment] 2023-11-27 14:18
have to disable XYK on ui side ..

**Comment by green-jay** [comment] 2023-11-28 07:49
problem also for non xyk trades, let's see if that fixes it

**Comment by green-jay** [comment] 2023-11-28 10:53
still a problem @nohaapav

**Comment by DuriSK** [comment] 2024-03-26 17:38
Cannot reproduce, seems like it has been fixed by number of EVM fixes

**Closed by DuriSK** 2024-03-26 17:38 UTC
